// MystSafe is a secret vault with anonymous access and zero activity tracking protected by cryptocurrency-grade tech.
// 
//     Copyright (C) 2024-2025 MystSafe, NeoSoft99
// 
//     MystSafe: The Only Privacy-Preserving Password Manager.
//     https://mystsafe.com
// 
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as
//     published by the Free Software Foundation, either version 3 of the
//     License, or (at your option) any later version.
// 
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//     See the GNU Affero General Public License for more details.
// 
//     You should have received a copy of the GNU Affero General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Fido2NetLib.Objects;

/// <summary>
/// AttestationConveyancePreference
/// https://www.w3.org/TR/webauthn-2/#enum-attestation-convey
/// </summary>
[JsonConverter(typeof(FidoEnumConverter<AttestationConveyancePreference>))]
public enum AttestationConveyancePreference
{
    /// <summary>
    /// This value indicates that the Relying Party is not interested in authenticator attestation. For example, in order to potentially avoid having to obtain user consent to relay identifying information to the Relying Party, or to save a roundtrip to an Attestation CA.
    /// This is the default value.
    /// </summary>
    [EnumMember(Value = "none")]
    None,

    /// <summary>
    /// This value indicates that the Relying Party prefers an attestation conveyance yielding verifiable attestation statements, but allows the client to decide how to obtain such attestation statements. The client MAY replace the authenticator-generated attestation statements with attestation statements generated by an Anonymization CA, in order to protect the user’s privacy, or to assist Relying Parties with attestation verification in a heterogeneous ecosystem.
    /// </summary>
    [EnumMember(Value = "indirect")]
    Indirect,

    /// <summary>
    /// This value indicates that the Relying Party wants to receive the attestation statement as generated by the authenticator.
    /// </summary>
    [EnumMember(Value = "direct")]
    Direct,

    /// <summary>
    /// This value indicates that the Relying Party wants to receive an attestation statement that may include uniquely identifying information.
    /// </summary>
    [EnumMember(Value = "enterprise")]
    Enterprise
}
